name: .NET
description: "[.NET](https://en.wikipedia.org/wiki/.NET) is a managed computer software framework for Windows, Linux, and macOS operating systems. It is a cross-platform successor to .NET Framework."