name: pull request

on:
  pull_request:
    branches: [ master ]

concurrency:
  group: pull-request-${{ github.ref }}
  cancel-in-progress: true

jobs:
  syntax-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - run: make install
      - run: make awesome_lint
      - run: make export_markdown
